name:                rtfelementparser
version:             0.1.0.0
github:              "githubuser/RTFParser"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/RTFElementParser#readme>

dependencies:
# - aeson >= 2 && <3
# - async >= 2.2 && < 3
# - attoparsec > 0.10 && < 0.20
- base >= 4.14 && < 5
- bytestring >=0.10 && <0.12
- containers >= 0.6 && < 0.7
# - deepseq >= 1.4 && < 1.5
# - exceptions >= 0.10 && < 0.11
- extra >=1.5 && <1.8
# - fourmolu >= 0.8 && < 1
- hlint >= 3.4 && < 4
- megaparsec >= 9 && < 10
- parser-combinators >= 1 && < 2
# - lens > 5 && < 6
- mtl >= 2.0 && < 2.3
# - safe-exceptions > 0.1.6 && < 0.2
# - template-haskell >=2.18 && <3
# - transformers >= 0.5 && < 0.6
# - transformers-base >= 0.4 && < 1
- text >=1.2 && <3
- text-show >=3.0 && <4

ghc-options:
- -rtsopts=all
- -fprof-auto
- -fprof-auto-top
- -fprof-auto-calls
- -fprof-auto-exported
- -fprof-auto-calls
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded 
- -Werror           # Warning as error


# NOTE: "language" field not recognized?
# default-language: Haskell2010
# language: Haskell2010

default-extensions:
- Haskell2010
- ConstraintKinds
- DataKinds
- DeriveAnyClass
- DeriveFoldable
- DeriveFunctor
- DeriveGeneric
- DeriveTraversable
- DeriveDataTypeable
- DerivingStrategies
- DerivingVia
- ExplicitForAll
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GADTs
- GeneralizedNewtypeDeriving
- ImportQualifiedPost
- InstanceSigs
- LambdaCase
- MultiParamTypeClasses
- RankNTypes
- RecordWildCards
- OverloadedStrings
- ScopedTypeVariables
- StandaloneDeriving
- StandaloneKindSignatures
- StrictData
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeOperators
- TypeFamilyDependencies
- TypeSynonymInstances


library:
  source-dirs: ./lib

tests:
  main-test: 
    main:               Main.hs
    source-dirs:      ./test
    dependencies: 
      - lens > 5 && < 6
      - tasty >= 0.11 && < 1.6
      - tasty-hspec >= 1.1 && < 1.3
      - hspec >= 0.1 && <= 3
      - hedgehog > 1 && < 2
      - tasty-hedgehog >= 0.1 && <= 1.4
      - template-haskell >=2.18 && <3

